name: CI
on: [push, pull_request]
jobs:
  builds:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq nasm pypy3
      - name: install python dependencies
        run: |
          pip3 install mypy
      - name: print version of pythons
        run: |
          python3 --version
          pypy3 --version
      - name: run tests
        run: |
          mypy ./porth.py
          mypy ./test.py
          pypy3 ./test.py
          pypy3 ./test.py -f ./examples/
