name: CI
on: [push, pull_request]
jobs:
  builds:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq nasm gcc cmake g++
      - name: install python dependencies
        run: |
          pip install mypy
      - name: run tests
        run: |
          mypy ./porth.py
          mypy ./test.py
          python ./test.py
          python ./test.py -f ./examples/
